name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please provide as much detail as possible to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a workflow with...
        2. Run command '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Configuration
      description: If applicable, paste your workflow YAML file or the relevant parts
      placeholder: |
        ```yaml
        name: example-workflow
        # ... your workflow configuration
        ```
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any error messages or logs
      placeholder: |
        ```
        Error: ...
        ```
      render: shell

  - type: dropdown
    id: version
    attributes:
      label: Wayfinder Version
      description: What version of wayfinder are you using?
      options:
        - "0.1.0"
        - "main/latest"
        - "other (specify in additional context)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - "Linux"
        - "macOS"
        - "Windows"
        - "Other (specify in additional context)"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version (if building from source)
      description: Output of `rustc --version`
      placeholder: "rustc 1.70.0 (90c541806 2023-05-31)"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this bug hasn't been reported already
          required: true
        - label: I have included all relevant information requested above
          required: true
        - label: I am willing to test a fix for this issue if provided
          required: false