name: ❓ Question
description: Ask a question about using Wayfinder
title: "[Question]: "
labels: ["question", "needs-response"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about using Wayfinder? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: I'm trying to understand how to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What area does your question relate to?
      options:
        - "Getting started"
        - "Workflow configuration"
        - "Template engine"
        - "Task types"
        - "CLI usage"
        - "Installation/setup"
        - "Performance"
        - "Troubleshooting"
        - "Best practices"
        - "Integration with other tools"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about what you're trying to achieve
      placeholder: |
        I'm working on...
        My goal is to...
        I've tried...

  - type: textarea
    id: current-approach
    attributes:
      label: Current Approach
      description: If applicable, show what you've tried so far
      placeholder: |
        ```yaml
        # My current workflow configuration
        name: my-workflow
        # ...
        ```
      render: yaml

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What are you hoping to accomplish?
      placeholder: I want to be able to...

  - type: input
    id: wayfinder-version
    attributes:
      label: Wayfinder Version
      description: What version are you using?
      placeholder: "0.1.0"

  - type: checkboxes
    id: resources-checked
    attributes:
      label: Resources Checked
      description: Have you checked these resources?
      options:
        - label: I have read the documentation
          required: false
        - label: I have looked at the example workflows
          required: false
        - label: I have searched existing issues and discussions
          required: false
